# Generated by Django 5.1.1 on 2024-10-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_formacion_asistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='formacion',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Formacion',
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
