# Generated by Django 5.0.6 on 2024-06-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_categories_alter_post_image_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(to='blog.category'),
        ),
    ]
