# Generated by Django 5.0.6 on 2024-07-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_mensaje_asunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='asunto',
            field=models.CharField(max_length=255),
        ),
    ]
