# Generated by Django 5.0.6 on 2024-07-01 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0003_alter_mensaje_asunto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='remitente',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='fecha_envio',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='contenido',
            new_name='mensaje',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='asunto',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='leido',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='sala',
            field=models.CharField(default='public', max_length=255),
        ),
    ]
